version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: vladik
      MONGO_INITDB_ROOT_PASSWORD: kotikvacia
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vladik
      ME_CONFIG_MONGODB_ADMINPASSWORD: kotikvacia
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/