###

# Фильмы
## Добавить новый фильм
POST http://localhost:8000/movies/create HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZsYWRla0B2ay5jb20iLCJpZCI6IjYzYzE5OTdkNzRiNjJiYWZmMDdkNGIyYSIsImlhdCI6MTY3MzYzMjE0NSwiZXhwIjoxNjczODA0OTQ1fQ.QOSlczvhMOLunlV2pwF6ZGap8sJ4nK3bEtN6p1ZOPHQ

{
  "title": "Авиатор",
  "description": "Кисик государство устраивает игры на выживание, за которыми в прямом эфире следит весь мир.",
  "publishingDate": "2022-10-21T22:55:33.903Z",
  "genre": "thriller",
  "releaseYear": 2013,
  "rating": 7,
  "commentsCount": 12,
  "previewPath": "https://www.what-to-watch.ru/hunger_games_preview",
  "moviePath": "https://www.what-to-watch.ru/hunger_games",
  "actors": [
    "Дженнифер Лоуренс",
    "Джош Хатчерсон",
    "Лиам Хемсворт"
  ],
  "director": "Гэри Росс",
  "duration": 70,
  "posterPath": "aviator.jpg",
  "backgroundImagePath": "OG9SaAd2MsLsln8cdBWAi.jpeg",
  "backgroundColor": "green"
}

###

## Редактирование карточки фильма
PATCH http://localhost:8000/movies/63c29a0483e4f0e1a55550c7 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZsYWRla0B2ay5jb20iLCJpZCI6IjYzYzE5OTdkNzRiNjJiYWZmMDdkNGIyYSIsImlhdCI6MTY3MzY5ODI3NywiZXhwIjoxNjczODcxMDc3fQ.FtuZJ0TTy3SyB4l4uP2IxacYL8s7mKlo4-3HQpkbqFs

{
  "title": "Король лев",
  "description": "У величественного Короля-Льва Муфасы рождается наследник по имени Симба. Уже в детстве любознательный малыш становится жертвой интриг своего завистливого дяди Шрама, мечтающего о власти. Симба познаёт горе утраты, предательство и изгнание, но в конце концов обретает верных друзей и находит любимую. Закалённый испытаниями, он в нелёгкой борьбе отвоёвывает своё законное место в «Круге жизни», осознав, что значит быть настоящим Королём.",
  "publishingDate": "2022-10-22T22:55:33.903Z",
  "genre": "drama",
  "releaseYear": 2013,
  "previewPath": "https://www.what-to-watch.ru/lion_ling_preview",
  "moviePath": "https://www.what-to-watch.ru/lion_king",
  "actors": [
    "Джеймс Эрл Джонс",
    "Мэттью Бродерик",
    "Джонатан Тейлор Томас"
  ],
  "director": "Роджер Алерс",
  "duration": 12,
  "posterPath": "lion_king_poster.jpg",
  "backgroundImagePath": "lion_king_bg.jpg",
  "backgroundColor": "orange",
  "isPromo": true
}

###

## Удаление карточки фильма
DELETE http://localhost:8000/movies/63c295e5b577c08e2073c25f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZsYWRpa0B2ay5jb20iLCJpZCI6IjYzYzE5NjJiNzRiNjJiYWZmMDdkNGFjZSIsImlhdCI6MTY3MzYzMTMzMCwiZXhwIjoxNjczODA0MTMwfQ.7GpFXSTgboQaaDDFIZUWEpbRqxm-KwPd6jasPvQ4M-U

###

## Получить список фильмов
GET http://localhost:8000/movies HTTP/1.1
Accept: application/json

###

## Получение списка фильмов определенного жанра
GET http://localhost:8000/movies?genre=drama HTTP/1.1
Accept: application/json

###

## Получение детальной информации по фильму
GET http://localhost:8000/movies/63c29870298bc7e1ffc50056 HTTP/1.1
Accept: application/json

###

## Получение промо-фильма
GET http://localhost:8000/movies/promo HTTP/1.1
Accept: application/json

###

## Получить список фильмов «К просмотру»
GET http://localhost:8000/users/to_watch HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZsYWRla0B2ay5jb20iLCJpZCI6IjYzYzE5OTdkNzRiNjJiYWZmMDdkNGIyYSIsImlhdCI6MTY3MzY5NzU2MCwiZXhwIjoxNjczODcwMzYwfQ.IhQ_ChT1zB00ENBhZME1VJ692lNLawIBP-EJ0pnuEow

###

## Добавить фильм в список «К просмотру»
POST http://localhost:8000/users/to_watch HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZsYWRla0B2ay5jb20iLCJpZCI6IjYzYzE5OTdkNzRiNjJiYWZmMDdkNGIyYSIsImlhdCI6MTY3MzY5NzU2MCwiZXhwIjoxNjczODcwMzYwfQ.IhQ_ChT1zB00ENBhZME1VJ692lNLawIBP-EJ0pnuEow

{
  "movieId": "63c1969174b62baff07d4adb"
}

###

## Удалить фильм из списка «К просмотру»
DELETE http://localhost:8000/users/to_watch HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXJAbWFpbC5ydSIsImlkIjoiNjNiZGM5MWU2OTk5OTY5YWY2MmI3MTBhIiwiaWF0IjoxNjczNDgwNTEyLCJleHAiOjE2NzM2NTMzMTJ9.hbxFnkOA3q99Ob2UVricBjd0l80WB-MgUpMGe4VVUtk

{
  "movieId": "63bf39c669e4b4d4bf20a1e5"
}

###

# Комментарии
## Получить список комментариев для определённого фильма
GET http://localhost:8000/movies/63c1969174b62baff07d4adb/comments HTTP/1.1
Accept: application/json

###

## Добавить новый комментарий к фильму
POST http://localhost:8000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZsYWRpa0B2ay5jb20iLCJpZCI6IjYzYzE5NjJiNzRiNjJiYWZmMDdkNGFjZSIsImlhdCI6MTY3MzYzMTMzMCwiZXhwIjoxNjczODA0MTMwfQ.7GpFXSTgboQaaDDFIZUWEpbRqxm-KwPd6jasPvQ4M-U

{
  "text": "Король Левик",
  "rating": 10,
  "movieId": "63c1969174b62baff07d4adb"
}

###

# Пользователи
## Создание нового пользователя
POST http://localhost:8000/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=DataToLogin

--DataToLogin
Content-Disposition: form-data; name="email"
Content-Type: text/plain

vladeeek@vk.com
--DataToLogin
Content-Disposition: form-data; name="name"
Content-Type: text/plain

vladik
--DataToLogin
Content-Disposition: form-data; name="password"
Content-Type: text/plain

123456
--DataToLogin
Content-Disposition: form-data; name="avatar"; filename="Владольф.jpg"
Content-Type: image/jpeg

< /Users/mac/Desktop/Владольф.jpg
--DataToLogin--

###

## Отправка аватарки пользователя
POST http://localhost:8000/users/63c1997d74b62baff07d4b2a/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----VladikAvatar
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZsYWRla0B2ay5jb20iLCJpZCI6IjYzYzE5OTdkNzRiNjJiYWZmMDdkNGIyYSIsImlhdCI6MTY3MzY5NjgwNSwiZXhwIjoxNjczODY5NjA1fQ.iUYM9pzCIjMZtGGoSJmLgdgO_Y-uwpc_IceoVvvBcI4

------VladikAvatar
Content-Disposition: form-data; name="avatar"; filename="Владольф.png"
Content-Type: image/png

< /Users/mac/Desktop/Владольф.png
------VladikAvatar--

###

## Обновление статики

POST http://localhost:8000/users/static HTTP/1.1
Content-Type: multipart/form-data; boundary=----NewStaticFile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZsYWRla0B2ay5jb20iLCJpZCI6IjYzYzE5OTdkNzRiNjJiYWZmMDdkNGIyYSIsImlhdCI6MTY3MzY5NjgwNSwiZXhwIjoxNjczODY5NjA1fQ.iUYM9pzCIjMZtGGoSJmLgdgO_Y-uwpc_IceoVvvBcI4

------NewStaticFile
Content-Disposition: form-data; name="static"; filename="Владольф.jpg"
Content-Type: image/jpeg

< /Users/mac/Desktop/Владольф.jpg
------NewStaticFile--

###

## Вход в закрытую часть приложения
POST http://localhost:8000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "vladek@vk.com",
  "password": "123456"
}

###

## Проверка токена пользователя
GET http://localhost:8000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InZsYWRla0B2ay5jb20iLCJpZCI6IjYzYzE5OTdkNzRiNjJiYWZmMDdkNGIyYSIsImlhdCI6MTY3MzY5NjgwNSwiZXhwIjoxNjczODY5NjA1fQ.iUYM9pzCIjMZtGGoSJmLgdgO_Y-uwpc_IceoVvvBcI4
