export const Component = {
  Application: Symbol.for('Application'),
  Logger: Symbol.for('Logger'),
  ConfigInterface: Symbol.for('ConfigInterface'),
  DBInterface: Symbol.for('DBInterface'),
  UserService: Symbol.for('UserService'),
  FilmServiceInterface: Symbol.for('FilmServiceInterface'),
  CommentServiceInterface: Symbol.for('CommentServiceInterface'),
  FilmModel: Symbol.for('FilmModel'),
  CommentModel: Symbol.for('CommentModel'),
  UserModel: Symbol.for('UserModel'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  FilmController: Symbol.for('FilmController'),
  UserController: Symbol.for('UserController'),
  CommentController: Symbol.for('CommentController'),
};
